{
	page_title: 'Guidelines',
	article: {
		title: 'Temple Guidelines',
		$text_customtype: 'wysiwyg',
		text: '<ol><li>All activities shall be in keeping with the dignity and respect for the sanctity of a holy place and according to Hindu Traditions. Behaviors in and around the temple facility not conforming to the sanctity of temple, the Hindu traditions and disturbing to the community at large will not be tolerated. &nbsp;&nbsp;</li><li>Before entering the worship area, please remove all footwear/winter coats and place them in the designated area.</li><li>No one is allowed in the sanctum area except the priest conducting the worship and volunteers helping the priest.</li><li>Please maintain silence in the temple (including hallways) especially when pooja services are in progress.&nbsp;</li><li>Please contact temple front desk staff (or priest if no staff is available) for any information about puja services.&nbsp;</li><li>Please do not leave the children unsupervised in the temple.&nbsp;</li><li>Please help us maintain the temple clean by properly disposing of all waste at appropriate waste baskets. &nbsp;&nbsp;</li><li>Please keep the cell phones and pagers in silent or vibrate mode.</li><li>All special pooja services, religious services (in the temple or outside the temple) should be confirmed through the HTBN management.&nbsp;</li><li>Do not change heating and cooling system of the facility.</li><li>Only trained persons should use the PA system and other equipment. &nbsp;</li><li>No smoking, no alcoholic beverages or chewing gum in the temple premises.&nbsp;</li><li>All non-monetary items or donations require approval by the temple management.&nbsp;</li><li>No items shall be taken or removed from temple premises by any individual.&nbsp;</li><li>Prasad could be served in the prayer hall but all other food must be served in the dining area.</li><li>Only vegetarian food without onion and garlic will be served in the temple area.&nbsp;</li><li>No outside food allowed unless permitted by HTBN management.&nbsp;</li><li>No pets allowed in the temple premises unless medical necessity.</li><li>No soliciting in the temple premises.&nbsp;</li><li>All devotees must assume the legal liability and responsibility. The board of trustees will not be responsible for any injury or lost or damaged personal items.&nbsp;</li><li>Anyone not conforming to HTBN guideline will be escorted out of the temple premises.&nbsp;</li></ol>',
		$title_undefined: 'Temple Guidelines',
		$text_undefined: '1.	All activities shall be in keeping with the dignity and respect for the sanctity of a holy place and according to Hindu Traditions. Behaviors in and around the temple facility not conforming to the sanctity of temple, the Hindu traditions and disturbing to the community at large will not be tolerated. \n2.	Before entering the worship area, please remove all footwear / winter coats and place them in the designated area. \n3.	No one is allowed in the sanctum area except the priest conducting the worship and volunteers helping the priest \n4.	Please maintain silence in the temple (including hallways) especially when pooja services are in progress. \n5.	Please contact temple front desk staff (or priest if no staff is available) for any information about puja services. \n6.	Please do not leave the children unsupervised in the temple. \n7.	Please help us maintaining the temple clean by properly disposing of all waste at appropriate waste baskets. \n8.	Please keep the cell phones and pagers in silent or vibrate mode. \n9.	All special pooja services, religious services (in the temple or outside the temple) should be confirmed through the HTBN management. \n10.	Do not change heating and cooling system of the facility. \n11.	Only trained persons should use the PA system and other equipment. \n12.	No smoking, no alcoholic beverages or chewing gum in the temple premises. \n13.	All non-monetary items or donations require approval by the temple management. \n14.	No items shall be taken or removed from temple premises by any individual. \n15.	Prasad could be served in the prayer hall but all other food must be served in dining area. \n16.	Only vegetarian food without onion and garlic will be served in the temple area. \n17.	No outside food allowed unless permitted by HTBN management. \n18.	No pets allowed in the temple premises unless medical necessity. \n19.	No soliciting in the temple premises. \n20.	All devotees must assume the legal liability and responsibility. The board of trustees will not be responsible for any injury or lost or damaged personal items. \n21.	Anyone not conforming to HTBN guideline will be escorted out of the temple premises.'
	},
	$page_title_undefined: 'Guidelines'
}